from __future__ import annotations

import json
import shlex
from collections.abc import Iterable, Mapping
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

ALLOW = "allow"
PROMPT = "prompt"
FORBIDDEN = "forbidden"

CATALOG_BUCKET_DECISIONS: tuple[tuple[str, str], ...] = (
    ("base_permissions", ALLOW),
    ("base_asks", PROMPT),
    ("base_denies", FORBIDDEN),
)

NEVER_ALLOWED_PROGRAMS: frozenset[str] = frozenset(
    {"rm", "rmdir", "shred", "dd", "mkfs", "sudo", "sudoedit", "doas", "pkexec"}
)

CATALOG_RELPATH = Path("skills") / "upgrade-cleanup" / "projects.yaml"
RULES_RELPATH = Path("codex") / "rules" / "dev10x.rules"

_SHELL_RULE_PREFIX = "Bash("
_UNMAPPABLE_CHARACTERS = frozenset("*?[]{}~$`")

_HEADER = (
    "# Generated by `dev10x permission codex-rules` from "
    "skills/upgrade-cleanup/projects.yaml — do not edit by hand.\n"
    "# Codex loads rules only from ~/.codex/rules/ or <project>/.codex/rules/;\n"
    "# plugins cannot bundle them, so copy or symlink this file there.\n"
)


@dataclass(frozen=True)
class CodexRule:
    pattern: tuple[str, ...]
    decision: str
    source: str


@dataclass(frozen=True)
class SkippedRule:
    source: str
    decision: str
    reason: str


@dataclass
class CodexRulesTranslation:
    rules: list[CodexRule] = field(default_factory=list)
    skipped: list[SkippedRule] = field(default_factory=list)


def translate_rule(source: str, decision: str) -> CodexRule | SkippedRule | None:
    if not (source.startswith(_SHELL_RULE_PREFIX) and source.endswith(")")):
        return None
    body = source[len(_SHELL_RULE_PREFIX) : -1]

    def skip(reason: str) -> SkippedRule:
        return SkippedRule(source=source, decision=decision, reason=reason)

    if not body.endswith(":*"):
        return skip("exact-match or catch-all shape; a Codex prefix_rule would widen it")
    prefix = body[:-2].strip()
    if _UNMAPPABLE_CHARACTERS & set(prefix):
        return skip("glob, home or variable expansion has no Codex token equivalent")
    try:
        tokens = tuple(shlex.split(prefix))
    except ValueError:
        return skip("prefix does not tokenize as a shell command")
    if not tokens:
        return skip("empty command prefix")
    if len(tokens) > 1 and tokens[-1].startswith("/"):
        return skip(
            "trailing path was a string prefix covering its children; Codex matches "
            "the exact token only"
        )
    if decision == ALLOW and Path(tokens[0]).name in NEVER_ALLOWED_PROGRAMS:
        return skip("destructive or privileged program is never auto-approved")
    return CodexRule(pattern=tokens, decision=decision, source=source)


def translate_catalog(catalog: Mapping[str, Any]) -> CodexRulesTranslation:
    translation = CodexRulesTranslation()
    seen: set[tuple[tuple[str, ...], str]] = set()
    for bucket, decision in CATALOG_BUCKET_DECISIONS:
        for source in catalog.get(bucket) or []:
            if not isinstance(source, str):
                continue
            outcome = translate_rule(source, decision)
            if outcome is None:
                continue
            if isinstance(outcome, SkippedRule):
                translation.skipped.append(outcome)
                continue
            key = (outcome.pattern, outcome.decision)
            if key in seen:
                continue
            seen.add(key)
            translation.rules.append(outcome)
    return translation


def _render_rule(rule: CodexRule) -> str:
    pattern = ", ".join(json.dumps(token) for token in rule.pattern)
    return (
        "prefix_rule(\n"
        f"    pattern = [{pattern}],\n"
        f"    decision = {json.dumps(rule.decision)},\n"
        f"    justification = {json.dumps('Dev10x catalog: ' + rule.source)},\n"
        ")\n"
    )


def render_rules(rules: Iterable[CodexRule]) -> str:
    return _HEADER + "".join("\n" + _render_rule(rule) for rule in rules)
